// SPDX-License-Identifier: MIT
// AuthoringSchemaGenerator.cs —— [Component] 声明式 Schema 生成器（P2.4）
//
// 收集程序集内全部 [Baize.Authoring.Component] 标注的 struct，
// 生成唯一的 AuthoringSchemaRegistration.RegisterAll(schema) 入口 +
// 每组件一个强类型 Schema 子类（字段读写 switch，可读可单步）。
// 与 FeatureManifestGenerator 同一哲学：声明即注册、无运行时反射、additive-only。

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Baize.Ecs.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class AuthoringSchemaGenerator : IIncrementalGenerator
{
	private const string ComponentAttributeMetadataName = "Baize.Authoring.ComponentAttribute";
	private const string Category = "Baize.Ecs.Generator";

	private static readonly DiagnosticDescriptor InvalidComponentDeclaration = new(
		"BAIZEECSGEN020",
		"Component 声明不受支持",
		"[Component] 标注的 '{0}' 必须是非 generic、非 ref 的 struct",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor ReadonlyComponentNotSupported = new(
		"BAIZEECSGEN021",
		"readonly struct 无法参与 W1 字段编辑",
		"[Component] 标注的 '{0}' 是 readonly struct——W1 需要按字段改写组件值，请去掉 readonly",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor UnsupportedFieldType = new(
		"BAIZEECSGEN022",
		"字段类型不受支持",
		"[Component] '{0}' 的字段 '{1}' 类型为 '{2}'；支持 int/uint/long/ulong/float/double/bool/string/enum",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor PrivateFieldNotSupported = new(
		"BAIZEECSGEN023",
		"private 字段不受支持",
		"[Component] '{0}' 的字段 '{1}' 是 private——生成代码无法访问，请至少改为 internal",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor MissingEngineContract = new(
		"BAIZEECSGEN024",
		"未实现引擎组件契约",
		"[Component] '{0}' 必须实现 Friflo.Engine.ECS.IComponent 或 ITag（组件定义 W1/W2 一份两用）",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor ReadonlyFieldNotSupported = new(
		"BAIZEECSGEN025",
		"readonly 字段无法参与 W1 编辑",
		"[Component] '{0}' 的字段 '{1}' 是 readonly——生成代码无法按字段改写，请去掉 readonly 或不标注 [Component]",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor NestedContainerNotSupported = new(
		"BAIZEECSGEN026",
		"嵌套容器不受支持",
		"[Component] '{0}' 不能声明在泛型或不可见（private/protected）的嵌套类型内——生成代码无法引用该类型",
		Category,
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var candidates = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				ComponentAttributeMetadataName,
				static (node, _) => node is TypeDeclarationSyntax,
				static (attributeContext, _) =>
					ComponentCandidate.Create((INamedTypeSymbol)attributeContext.TargetSymbol))
			.Collect();

		context.RegisterSourceOutput(candidates, Execute);
	}

	private static void Execute(SourceProductionContext context, ImmutableArray<ComponentCandidate?> candidates)
	{
		var components = candidates
			.Where(candidate => candidate is not null)
			.Select(candidate => candidate!)
			.OrderBy(candidate => candidate.FullyQualifiedName, StringComparer.Ordinal)
			.ToList();

		foreach (var component in components)
		{
			foreach (var diagnostic in component.Diagnostics)
			{
				context.ReportDiagnostic(diagnostic);
			}
		}

		// 有任何错误的组件不参与生成（避免半残 Schema 掩盖根因）；无组件则不出文件
		var valid = components.Where(component => component.IsValid).ToList();
		if (valid.Count == 0) return;


		context.AddSource("Baize_Authoring_AuthoringSchemaRegistration.g.cs",
			SourceText.From(Render(valid), Encoding.UTF8));
	}

	private static string Render(List<ComponentCandidate> components)
	{
		var builder = new StringBuilder();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("// SPDX-License-Identifier: MIT");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();
		builder.AppendLine("// 由 AuthoringSchemaGenerator 从 [Baize.Authoring.Component] 标注生成——不要手改。");
		builder.AppendLine("public static class AuthoringSchemaRegistration");
		builder.AppendLine("{");

		builder.AppendLine("\t/// <summary>把本程序集全部 [Component] 组件的 Schema 注册进 W1 世界（声明即注册，无反射）。</summary>");
		builder.AppendLine("\tpublic static void RegisterAll(global::Baize.Authoring.AuthoringSchema schema)");
		builder.AppendLine("\t{");
		foreach (var component in components)
		{
			builder.Append("\t\tschema.Register(new ").Append(component.SchemaClassName).AppendLine("());");
		}
		builder.AppendLine("\t}");
		builder.AppendLine();

		foreach (var component in components)
		{
			RenderSchemaClass(builder, component);
			builder.AppendLine();
		}

		builder.AppendLine("}");
		return builder.ToString();
	}

	private static void RenderSchemaClass(StringBuilder builder, ComponentCandidate component)
	{
		string componentType = component.FullyQualifiedName;

		builder.AppendLine("\t/// <summary>组件 " + component.MetadataName + " 的 Schema：字段元数据 + 强类型读写。</summary>");
		builder.Append("\tprivate sealed class ").Append(component.SchemaClassName)
			.Append(" : global::Baize.Authoring.ComponentSchemaBase").AppendLine();
		builder.AppendLine("\t{");

		// 构造器：类型 + 字段元数据
		// 构造器：类型 + 字段元数据（无字段组件用显式类型空数组，避免 new[] 无法推断）
		if (component.Fields.Count == 0)
		{
			builder.AppendLine("\t\tpublic " + component.SchemaClassName + "() : base(typeof(" + componentType
				+ "), global::System.Array.Empty<global::Baize.Authoring.SchemaField>())");
		}
		else
		{
			builder.AppendLine("\t\tpublic " + component.SchemaClassName + "() : base(typeof(" + componentType + "), new[]");
			builder.AppendLine("\t\t{");
			foreach (var field in component.Fields)
			{
				builder.Append("\t\t\tnew global::Baize.Authoring.SchemaField(\"")
					.Append(field.Name).Append("\", typeof(").Append(field.TypeFullName)
					.Append("), ").Append(field.Index).AppendLine("),");
			}
			builder.AppendLine("\t\t})");
		}
		builder.AppendLine("\t\t{");
		builder.AppendLine("\t\t}");
		builder.AppendLine();

		builder.AppendLine("\t\tpublic override object CreateDefault() => default(" + componentType + ");");
		builder.AppendLine();

		// 读路径：强类型 switch
		builder.AppendLine("\t\tpublic override object GetFieldRaw(object component, int index) => index switch");
		builder.AppendLine("\t\t{");
		foreach (var field in component.Fields)
		{
			builder.Append("\t\t\t").Append(field.Index).Append(" => ((")
				.Append(componentType).Append(")component).").Append(field.EscapedName);
			if (field.IsString)
			{
				// string 字段读出口统一归一：default(T) 的 null 不外泄（hash/序列化安全）
				builder.Append(" ?? string.Empty");
			}
			builder.AppendLine(",");
		}
		builder.AppendLine("\t\t\t_ => throw new global::System.ArgumentOutOfRangeException(nameof(index), index, \"字段索引越界\"),");
		builder.AppendLine("\t\t};");
		builder.AppendLine();

		// 写路径：C# 禁止 unbox 后直接改字段（CS0445），拷出→改→装箱替换（ref object 语义）
		builder.AppendLine("\t\tpublic override void SetFieldRaw(ref object component, int index, object value)");
		builder.AppendLine("\t\t{");
		builder.AppendLine("\t\t\tswitch (index)");
		builder.AppendLine("\t\t\t{");
		foreach (var field in component.Fields)
		{
			builder.Append("\t\t\t\tcase ").Append(field.Index).Append(": { var __typed = (")
				.Append(componentType).Append(")component; __typed.").Append(field.EscapedName)
				.Append(" = (").Append(field.TypeFullName).AppendLine(")value; component = __typed; break; }");
		}
		builder.AppendLine("\t\t\t\tdefault: throw new global::System.ArgumentOutOfRangeException(nameof(index), index, \"字段索引越界\");");
		builder.AppendLine("\t\t\t}");
		builder.AppendLine("\t\t}");
		builder.AppendLine("\t}");
	}

	/// <summary>单个候选组件的收集结果（验证在 transform 阶段完成，诊断延后上报）。</summary>
	private sealed class ComponentCandidate
	{
		public string FullyQualifiedName { get; private set; } = "";
		public string MetadataName { get; private set; } = "";
		public string SchemaClassName { get; private set; } = "";
		public List<SchemaFieldInfo> Fields { get; } = new();
		public List<Diagnostic> Diagnostics { get; } = new();
		public bool IsValid { get; private set; }

		public static ComponentCandidate? Create(INamedTypeSymbol symbol)
		{
			if (symbol.TypeKind != TypeKind.Struct || symbol.IsRefLikeType)
			{
				return Invalid(symbol, InvalidComponentDeclaration);
			}
			// 可见性/泛型度检查覆盖组件自身与全部嵌套容器：任一层 generic 或
			// 非 Public/Internal（private/protected/file）都会让全局生成类无法访问该类型
			if (symbol.Arity > 0 ||
				symbol.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
			{
				return Invalid(symbol, NestedContainerNotSupported);
			}
			for (INamedTypeSymbol? containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
			{
				if (containing.Arity > 0 || containing.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
				{
					return Invalid(symbol, NestedContainerNotSupported);
				}
			}
			if (symbol.IsReadOnly)
			{
				return Invalid(symbol, ReadonlyComponentNotSupported);
			}

			var candidate = new ComponentCandidate
			{
				FullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
				MetadataName = symbol.ToDisplayString(),
				SchemaClassName = Sanitize(symbol.Name) + "Schema_" + Fnv1a(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).ToString("X8"),
			};

			ValidateEngineContract(symbol, candidate);

			// 实例字段按声明顺序（词法位置兜底稳定排序）
			var fields = symbol.GetMembers().OfType<IFieldSymbol>()
				.Where(field => !field.IsStatic && !field.IsConst && !field.IsImplicitlyDeclared)
				.OrderBy(field => field.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
				.ToList();

			int index = 0;
			foreach (var field in fields)
			{
				if (field.DeclaredAccessibility == Accessibility.Private)
				{
					candidate.Diagnostics.Add(Diagnostic.Create(
						PrivateFieldNotSupported, field.Locations.FirstOrDefault(), candidate.MetadataName, field.Name));
					continue;
				}
				if (field.IsReadOnly)
				{
					// 非 readonly struct 也能声明 readonly 实例字段——生成代码无法改写，提前给出明确诊断
					candidate.Diagnostics.Add(Diagnostic.Create(
						ReadonlyFieldNotSupported, field.Locations.FirstOrDefault(), candidate.MetadataName, field.Name));
					continue;
				}
				if (!IsSupportedFieldType(field.Type))
				{
					candidate.Diagnostics.Add(Diagnostic.Create(
						UnsupportedFieldType, field.Locations.FirstOrDefault(),
						candidate.MetadataName, field.Name, field.Type.ToDisplayString()));
					continue;
				}

				candidate.Fields.Add(new SchemaFieldInfo(
					field.Name,
					EscapeIdentifier(field.Name),
					field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
					index,
					isString: field.Type.SpecialType == SpecialType.System_String));
				index++;
			}

			candidate.IsValid = candidate.Diagnostics.Count == 0;
			return candidate;

			static ComponentCandidate? Invalid(INamedTypeSymbol symbol, DiagnosticDescriptor descriptor)
			{
				var candidate = new ComponentCandidate
				{
					FullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
					MetadataName = symbol.ToDisplayString(),
					SchemaClassName = Sanitize(symbol.Name) + "Schema",
				};
				candidate.Diagnostics.Add(Diagnostic.Create(
					descriptor,
					symbol.Locations.FirstOrDefault() ?? Location.None,
					symbol.ToDisplayString()));
				return candidate;
			}
		}

		private static void ValidateEngineContract(INamedTypeSymbol symbol, ComponentCandidate candidate)
		{
			bool implementsContract = false;
			foreach (var iface in symbol.AllInterfaces)
			{
				string name = (iface.ContainingNamespace.IsGlobalNamespace ? "" : iface.ContainingNamespace.ToDisplayString() + ".")
					+ iface.Name;
				if (name is "Friflo.Engine.ECS.IComponent" or "Friflo.Engine.ECS.ITag")
				{
					implementsContract = true;
					break;
				}
			}
			if (!implementsContract)
			{
				candidate.Diagnostics.Add(Diagnostic.Create(
					MissingEngineContract,
					symbol.Locations.FirstOrDefault() ?? Location.None,
					symbol.ToDisplayString()));
			}
		}

		private static bool IsSupportedFieldType(ITypeSymbol type)
		{
			switch (type.SpecialType)
			{
				case SpecialType.System_Int32:
				case SpecialType.System_UInt32:
				case SpecialType.System_Int64:
				case SpecialType.System_UInt64:
				case SpecialType.System_Single:
				case SpecialType.System_Double:
				case SpecialType.System_Boolean:
				case SpecialType.System_String:
					return true;
			}
			return type.TypeKind == TypeKind.Enum;
		}

		private static string Sanitize(string name)
		{
			var safe = new StringBuilder(name.Length);
			foreach (char character in name)
			{
				safe.Append(char.IsLetterOrDigit(character) ? character : '_');
			}
			return safe.ToString();
		}

		/// <summary>C# 关键字标识符转义（@event 等）；与 Roslyn SyntaxFacts 规则一致。</summary>
		private static string EscapeIdentifier(string name)
		{
			var keyword = Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name);
			return keyword != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None ? "@" + name : name;
		}
	}

	private sealed class SchemaFieldInfo
	{
		public SchemaFieldInfo(string name, string escapedName, string typeFullName, int index, bool isString)
		{
			Name = name;
			EscapedName = escapedName;
			TypeFullName = typeFullName;
			Index = index;
		}

		public string Name { get; }

		/// <summary>生成代码中的字段访问名（C# 关键字字段加 @ 前缀；逻辑名仍是 Name）。</summary>
		public string EscapedName { get; }
		public string TypeFullName { get; }
		public int Index { get; }
		public bool IsString { get; }
	}

	private static uint Fnv1a(string value)
	{
		unchecked
		{
			uint hash = 2166136261;
			foreach (char character in value)
			{
				hash ^= character;
				hash *= 16777619;
			}
			return hash;
		}
	}
}
